spring.application.name=propfinder
spring.datasource.url=jdbc:postgresql://localhost:5432/propfinder
spring.datasource.username=propfinder
spring.datasource.password=propfinder

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=8080
